### DISCUSSION TITLE
How to set model other than `gpt-3.5-turbo`/`gpt-4-turbo`

### DISCUSSION THREAD

**Discussion by johnd0e** [darrenburns/elia#34] [Questions] [answered]
Specifically, I need bare `gpt-4`.

**Comment by darrenburns** [comment, marked as answer]
Add this to your config file:

```toml
[[models]]
name = "gpt-4"
```
