### DISCUSSION TITLE
api_base + api_key = provider

### DISCUSSION THREAD

**Discussion by johnd0e** [darrenburns/elia#38] [Ideas]
I need to configure several OpenAI-compatible models, all belonging to the same service. Currently, the only method is to explicitly specify the `api_base` and `api_key` for each model. 

However, it would be much more convenient if I could set up the `api_base` + `api_key` pair just once and then reuse it for all the models.
E.g.:
```toml
[[providers]]
name = "local"
api_base = "http://localhost:8080/v1"
api_key = "api-key-if-required"

[[models]]
name = "gpt-3.5-turbo"
provider = "local"

[[models]]
name = "gpt-4"
provider = "local"
```
