### DISCUSSION TITLE
setup with open webui through exposed(proxied?) ollama api

### DISCUSSION THREAD

**Discussion by abondis** [darrenburns/elia#85] [General]
Hi,
I just wanted to share how I set up elia to work with openwebui, through it's proxied ollama api:

in `~/.config/elia/config.toml`

```toml
[[models]]
id = "local"
name = "ollama_chat/llama3.2"
api_base = "http://<ip>:<port>/ollama"
api_key = "sk-<generated from openwebui's user settings>"
```
