### ISSUE TITLE
How to set model other than `gpt-3.5-turbo`/`gpt-4-turbo`

### ISSUE THREAD

**Issue by johnd0e** [darrenburns/elia#32]
Specifically, I need bare `gpt-4`.

**Comment by darrenburns** [comment]
Add this to your config file:

```toml
[[models]]
name = "gpt-4"
```
