### ISSUE TITLE
reading api key from a config file

### ISSUE THREAD

**Issue by thisismygitrepo** [darrenburns/elia#52]
Like many other tools, can we please have this one reading api key from the config file? as opposed from env vars or explicity passing.

**Comment by darrenburns** [comment]
You can pass `api_key` in a model definition in the config file. Something like this should work:

```toml
[[models]]
id = "my-gpt-3.5-turbo"
name = "gpt-3.5-turbo"
display_name = "My GPT 3.5 Turbo"
api_key = "something"
```
